export default {
    zh: {
        MENU_MARKET: '市场',
        MENU_COLLECTIONS: '系列',
        MENU_COLLECTIONS_ALL: '全部',
        MENU_COLLECTIONS_ART: '艺术',
        MENU_COLLECTIONS_SPORTS: '运动',
        MENU_COLLECTIONS_MUSIC: '音乐',
        MENU_COLLECTIONS_MOVIES: '电影',
        MENU_COLLECTIONS_PHOTOGRAPHY: '摄影',
        MENU_COLLECTIONS_FOOD: '美食',
        MENU_COLLECTIONS_STARS: '明星',
        MENU_CREATE: '创造',
        MENU_USER_PROFILE: '个人信息',
        MENU_USER_COLLECTIONS: '我的系列',
        MENU_USER_FAVORITES: '我的收藏',
        MENU_USER_SETTINGS: '设置',
        MENU_USER_SIGN_OUT: '退出登录',
        MENU_USER_BUTTON_ADD_FUNDS: '增加资金'
    },
    en:{
        MENU_MARKET: 'MARKET',
        MENU_COLLECTIONS: 'COLLECTIONS',
        MENU_COLLECTIONS_ALL: 'ALL',
        MENU_COLLECTIONS_ART: 'ART',
        MENU_COLLECTIONS_SPORTS: 'SPORTS',
        MENU_COLLECTIONS_MUSIC: 'MUSIC',
        MENU_COLLECTIONS_MOVIES: 'MOVIES',
        MENU_COLLECTIONS_PHOTOGRAPHY: 'PHOTOGRAPHY',
        MENU_COLLECTIONS_FOOD: 'FOOD',
        MENU_COLLECTIONS_STARS: 'STARS',
        MENU_CREATE: 'CREATE',
        MENU_USER_PROFILE: 'Profile',
        MENU_USER_COLLECTIONS: 'My Collections',
        MENU_USER_FAVORITES: 'My Favorites',
        MENU_USER_SETTINGS: 'Settings',
        MENU_USER_SIGN_OUT: 'Sign Out',
        MENU_USER_BUTTON_ADD_FUNDS: 'Add Funds'
    }
}